using System.Reflection;
using System.Text.Json;

namespace ERCTelemetry.Core.Tracks;

/// <summary>One circuit's centerline in flat metre space (x = east, y = north around
/// the circuit centroid), generated by tools/TrackLayoutGen from bacinger/f1-circuits
/// (MIT). Points form a closed ring.</summary>
public sealed record TrackLayout(
    float[] X,
    float[] Y,
    float LengthMetres)
{
    public int PointCount => X.Length;
}

/// <summary>Static lookup of the embedded track layouts, keyed by the game's Track enum
/// name (with or without the "F1_" prefix, case-insensitive) — the same normalization
/// the app-side TrackImage uses. Unknown tracks return false and every consumer keeps
/// its fallback rendering.</summary>
public static class TrackLayoutCatalog
{
    private const string ResourceName = "ERCTelemetry.Core.Tracks.track-layouts.json";

    private static readonly Lazy<IReadOnlyDictionary<string, TrackLayout>> Catalog = new(Load);

    public static bool TryGet(string? trackEnumName, out TrackLayout layout)
    {
        layout = null!;
        if (string.IsNullOrWhiteSpace(trackEnumName))
        {
            return false;
        }

        var name = trackEnumName;
        if (name.StartsWith("F1_", StringComparison.OrdinalIgnoreCase))
        {
            name = name[3..];
        }

        // Bridge the game's Track enum spelling to the catalog's circuit-name keys
        // (e.g. "Austria" → "spielberg"). The JSON is keyed by the bacinger/f1-circuits
        // names; F1Game.UDP 26 sends its own names for several circuits.
        if (GameNameToKey.TryGetValue(name, out var key))
        {
            name = key;
        }

        return Catalog.Value.TryGetValue(name, out layout!);
    }

    /// <summary>F1Game.UDP Track enum names that don't match the catalog's circuit-name
    /// keys (the JSON is keyed by bacinger/f1-circuits names, e.g. "spielberg" for
    /// Austria). Reverse variants reuse the same circuit layout — the fitter recovers
    /// the direction from the driven trail.</summary>
    private static readonly Dictionary<string, string> GameNameToKey = new(StringComparer.OrdinalIgnoreCase)
    {
        ["AbuDhabi"] = "yas_marina",
        ["Texas"] = "austin",
        ["Brazil"] = "interlagos",
        ["Austria"] = "spielberg",
        ["Mexico"] = "mexicocity",
        ["Azerbaijan"] = "baku",
        ["Madrid"] = "madring",
        ["SilverstoneReverse"] = "silverstone",
        ["AustriaReverse"] = "spielberg",
        ["ZandvoortReverse"] = "zandvoort",
    };

    private static IReadOnlyDictionary<string, TrackLayout> Load()
    {
        var assembly = Assembly.GetExecutingAssembly();
        using var stream = assembly.GetManifestResourceStream(ResourceName)
            ?? throw new InvalidDataException($"Embedded resource '{ResourceName}' is missing — run tools/TrackLayoutGen.");
        var doc = JsonDocument.Parse(stream);

        var catalog = new Dictionary<string, TrackLayout>(StringComparer.OrdinalIgnoreCase);
        foreach (var track in doc.RootElement.GetProperty("Tracks").EnumerateObject())
        {
            var xs = new List<float>();
            var ys = new List<float>();
            foreach (var point in track.Value.GetProperty("Points").EnumerateArray())
            {
                xs.Add((float)point[0].GetDouble());
                ys.Add((float)point[1].GetDouble());
            }

            catalog[track.Name] = new TrackLayout(
                xs.ToArray(),
                ys.ToArray(),
                (float)track.Value.GetProperty("LengthM").GetDouble());
        }

        return catalog;
    }
}